### ISSUE TITLE
Jail a ZFS dataset e.g., for Poudriere in a jail (request for comments)

### ISSUE THREAD

**Issue by hxw** [pizzamig/pot#105]
### Basic idea

Have a command that can attach a ZFS dataset below the jail's chroot and set it as jailed.
This would allow the jail to create/destroy child datasets. The pot start/stop would handle
the mount/unmount.

### Form of the commands

```sh
pot jail-dataset -p pot [-m mountpoint] -c dataset    # create new dataset and attach
pot jail-dataset -p pot [-m mountpoint] -a dataset    # attach existing dataset
pot jail-dataset -p pot -m mountpoint                 # alter mount point of current dataset
pot jail-dataset -p pot -d                            # detach current dataset, but keep it
pot jail-dataset -p pot -D                            # detach and destroy current dataset
```
Notes:
* create/attach can optionally set a mount point in the pot rather than de default `/usr/local/<dataset>` (the mount point is local to the jail)
* create would additionally preconfigure all necessary jail attributes for ZFS
* the **dataset** would be a simple name and effectively become `$POT_ZFS_ROOT/jails/$POT/m/$DATASET`
* only a single dataset would be supported for each pot, though inside the pot can create child dataset as it requires

### Current state

* I currently have a test version of the low level parts i.e., the set-attr/start/stop code and this is working for me and this builds on: Jail attribute #103
* I would appreciate some comments on the above command format

**Comment by pizzamig** [comment]
mmm, that seems a duplication of a feature already available.

fscomp are ZFS dataset. You can create them with the command `create-fscomp`
they can be used in one jail or shared between multiple jails, but they live independently
Exclusive usage to one jail/pot is a spacial case, that is supported.

to mount a dataset to a pot, the command `mount-in` can be used.
The "detach" feature is not available, tho.
fscomp can be destroyed with `destroy`

**Comment by hxw** [comment]
perhaps I need to look at how fs comp works, I had though it would only mount the data set externally and not delegate it into the jail. I will experiment further.
