### ISSUE TITLE
[BUG] Error message when creating clone

### ISSUE THREAD

**Issue by hny-gd** [pizzamig/pot#106]
**Describe the bug**
There is an error message (with obviously no further impact) when cloning a pot image to an alias network configuration. The clone is nonetheless created and seems to work fine.

**To Reproduce**
1. pot import -p traefik-consul-amd64-12_1 -t 1.1 -U https://potluck.honeyguide.net/traefik-consul
2. pot clone -P traefik-consul-amd64-12_1_1_1 -p traefik-consul-clone -N alias -i "em0|192.168.178.114"
3. Output shown:
```
grep: grep: No such file or directory
grep: ^ip: No such file or directory
```

**Expected behavior**
No error message being shown

**System configuration - if possible**
 - Happens on new systems with no adjusted pot.conf

** If network related **
 - `cat /etc/pf.conf`
```
nat-anchor pot-nat
rdr-anchor "pot-rdr/*"
```
 - `potnet show -v`
```
12:54:29 [ INFO] Insert network Some(10.192.0.0/10)
12:54:29 [ INFO] Insert broadcast Some(10.192.0.0/10)
12:54:29 [ INFO] Insert gateway Some(V4(10.192.0.1))
12:54:29 [ INFO] Insert dns Some(V4(10.192.0.2))
12:54:29 [ INFO] Insert pot V4(10.192.0.4)
12:54:29 [ INFO] Insert pot V4(10.192.0.6)
12:54:29 [ INFO] Insert pot V4(10.192.0.5)
Network topology:
	network : 10.192.0.0/10
	min addr: 10.192.0.0
	max addr: 10.255.255.255

Addresses already taken:
	10.192.0.0	
	10.192.0.1	default gateway
	10.192.0.2	dns
	10.192.0.4	consul-amd64-12_1_1_0
	10.192.0.5	nomad-server-amd64-12_1_1_0
	10.192.0.6	traefik-consul-amd64-12_1_1_1
	10.255.255.255	

Debug information
SystemConf {
    zfs_root: Some(
        "zroot/pot",
    ),
    fs_root: Some(
        "/opt/pot",
    ),
    network: Some(
        10.192.0.0/10,
    ),
    netmask: Some(
        V4(
            255.192.0.0,
        ),
    ),
    gateway: Some(
        V4(
            10.192.0.1,
        ),
    ),
    ext_if: Some(
        "em0",
    ),
    dns_name: Some(
        "dns",
    ),
    dns_ip: Some(
        V4(
            10.192.0.2,
        ),
    ),
}
```

**Additional context**
-

**Comment by Crest** [comment]
Please try again with the latest master branch. I suspect I've already fixed the typo (a missing backslash at the end of the line) that caused this behaviour. There hasn't been a release since the fix got commited.

**Comment by pizzamig** [comment]
Hi. Thanks for the bug report.
As Crest mentioned, this bug should be already fixed in master, but not yet available on a release.
Can you please check if with the latest `clone.sh` the error messages are going away?
I'm preparing the next release

**Comment by hny-gd** [comment]
Thanks a lot for the quick replies, @Crest and @pizzamig, the error indeed seems to have disappeared with the most current clone.sh.
