### ISSUE TITLE
Provide `pot.dns=off` setting to disable automatically overwriting jail resolv.conf on start

### ISSUE THREAD

**Issue by paulc** [pizzamig/pot#111]
**Is your feature request related to a problem? Please describe.**

Currently the `pot.dns` setting only supports `inherit` (copy resolv.conf from host) or `pot` (resolve via dedicated dns jail instance), and in particular on startup will always unilaterally overwrite /ets/resolv.conf in the jail.

There are a number of circumstances where it would be good to have more control than this. I have a specific requirement where I am using pot on a host with a single IPv4 address but a routable /64 IPv6 subnet. I am using pot to create multiple IPv6 only jails with separate IPv6 addresses aliased to the host network adaptor (using `pot create -p name -N alias -S ipv6 -i address`). This is really useful as I can just run ssh in the jails and connect to these directly using the IPv6 address. The only minor problem is that I need to list the IPv6 resolvers in the jail resolv.conf which are different to the host settings (need to remove the IPv4 resolvers). At the moment this isn't possible as `pot start` will overwrite the jail settings on boot (I had previously tried using `pot copy-in` to explicitly set resolv.conf however this is overwritten on start)

**Describe the feature you'd like to have**

Provide more control of the way pot handles setting the jail `resolv.conf`. 

As a minimum it would be good to add an `pot.dns=off` setting which would disable the automatic copying of `resolv.conf`. It might also be an option to also add a `pot.dns=file:/path/to/file` though this could just be done with a `copy-in` after the pot was created (which I think would be a cleaner solution)

**Describe potential alternatives or workaround you've considered (if any)**

It is possible to just reset the `resolv.conf` file either using copy-in from the host after starting the jail or adding an rc script in the jail, but this is a bit messy and anything that requires network access in the boot sequence would fail upto this point.

If you are happy with the concept of a `pot.dns=off` setting I'm happy to generate a pull request (would be fairly simple)

Regards, Paul

**Comment by pizzamig** [comment]
Hi Paul.
`resolv.conf` management is indeed an area that would benefit for some help.
Currently, `inherit` will copy the `resolv.conf` at `start`, to be more dynamic, especially when running on a laptop.
I agree that more options are needed (I have one machine with unboud and it's a scenario that is causing issues).
Starting with `off` as an additional value makes a lot of sense.
