### ISSUE TITLE
Pot with linux compatibility

### ISSUE THREAD

**Issue by LukeMauldin** [pizzamig/pot#116]
**Is your feature request related to a problem? Please describe.**
Does pot support FreeBSD jails with linux compatibility options? If so, I don't see it in the documentation?
According to https://www.freebsd.org/releases/12.2R/relnotes.html - FreeBSD 12.2 support running Linux in a jailed environment.  Would like to be able to use pot to configure linux jails.

**Comment by pizzamig** [comment]
theoretically, from `pot` point of view there should be no difference.
Do you know if there is a specific jail parameter that is needed to run Linux binaries in a jail that is not configurable via `pot`?

**Comment by LukeMauldin** [comment]
I can confirm this is a non-issue. Linux binaries are running in pot as I expect.
