### ISSUE TITLE
Support for setting hostname

### ISSUE THREAD

**Issue by LukeMauldin** [pizzamig/pot#118]
**Is your feature request related to a problem? Please describe.**
Need a way to control the hostname set in the pot.  Using pot through the nomad-pot-driver and so the generated pot names are very long and it causes the hostname put in pot.conf to be longer than 64 characters which breaks my application. 

**Describe the feature you'd like to have**
A way to instruct pot to set the hostname of a pot to just the hostname of the running machine or something similar.

**Describe potential alternatives or workaround you've considered (if any)**
My work-around was to update create.sh and clone.sh where hostname is written into pot.conf to be only the hostname of the machine rather than the full ID combined with the machine name.  Obviously this is not ideal because I have to remember to re-apply my changes when I update pot.

**Comment by pizzamig** [comment]
Hi.
currently, in create and clone the pot hostname is set as jailname.hostname to guarantee uniqueness across a the cluster.
However, I can see that it can be problematic and the nomad hash should be already unique.

As a solution, I can force a configurable max length for the pot hostname, with a default value of 64.
I've already encountered a similar issue with the pf anchor, so it should be relatively doable
