### ISSUE TITLE
[BUG] Bridge-based networking fails due to incomplete pf rules when POT_EXTIF has a private IP alias

### ISSUE THREAD

**Issue by BlueSpaceCanary** [pizzamig/pot#120]
**Describe the bug**
When creating a public-bridge or private-bridge pot, the generated NAT rules are something like

```
ext_if = "vtnet0"
localnet = "10.192.0.0/10"
nat on $ext_if from $localnet to any -> ($ext_if)
```

However, if `$ext_if` has a private range IP as an alias on it, this doesn't work (or at least not consistently). I tested, and reloading pf with the above changed to 

```
ext_if = "vtnet0"
localnet = "10.192.0.0/10"
nat on $ext_if from $localnet to any -> ($ext_if:0)
```

resolved my networking issues. This is an issue on, for example, DigitalOcean, where VMs are assigned both public and private IPs on their main external interface.

**To Reproduce**
1. Create digitalocean FreeBSD droplet
2. Install pot
3. Set `POT_EXTIF=vtnet0`
4. `sudo pot create -p foo -t single -b 12.2 -N public-bridge -i auto`
5. `sudo pot run foo`
6. `ping digitalocean.com`

**Expected behavior**
Either autoselect the correct IP on the interface or some sort of configuration like `POT_EXTADDR` to set it manually.

**System configuration - if possible**
 - All defaults except the interface name

** If network related **
 - `cat /etc/pf.conf`
 
 ```
% cat /etc/pf.conf
nat-anchor pot-nat
rdr-anchor "pot-rdr/*"
```  

 - `potnet show -v` 

 ```
% potnet show -v
02:56:40 [ INFO] Insert network Some(10.192.0.0/10)
02:56:40 [ INFO] Insert broadcast Some(10.192.0.0/10)
02:56:40 [ INFO] Insert gateway Some(10.192.0.1)
02:56:40 [ INFO] Insert dns Some(10.192.0.2)
02:56:40 [ INFO] Insert pot 10.192.0.3
Network topology:
	network : 10.192.0.0/10
	min addr: 10.192.0.0
	max addr: 10.255.255.255

Addresses already taken:
	10.192.0.0
	10.192.0.1	default gateway
	10.192.0.2	dns
	10.192.0.3	foo
	10.255.255.255

Debug information
SystemConf {
    zfs_root: Some(
        "zroot/pot",
    ),
    fs_root: Some(
        "/opt/pot",
    ),
    network: Some(
        10.192.0.0/10,
    ),
    netmask: Some(
        255.192.0.0,
    ),
    gateway: Some(
        10.192.0.1,
    ),
    ext_if: Some(
        "vtnet0",
    ),
    dns_name: Some(
        "dns",
    ),
    dns_ip: Some(
        10.192.0.2,
    ),
}
```

**Additional context**

**Comment by pizzamig** [comment]
Hi, thanks for reporting.
Honestly, I didn't see this coming, DO has quite an unusual solution.
In the **Expected behavior** section you mention as solution:
* autoselect the correct IP on the interface
* some sort of configuration like POT_EXTADDR to set it manually.
I have honestly some trouble to identify how to autoselect the "correct IP". Do you have any idea on how an autoselect algorithm should look like?
I would be more keen to an optional POT_EXTADDR to fix this issue.

**Comment by BlueSpaceCanary** [comment]
A config value definitely seems simplest. Guessing which is the right one based on whether it's a public range would be possible, I guess, but that seems needlessly complex.

**Comment by pizzamig** [comment]
The easy fix I'm going to add rapidly is to add :0 to extif, to avoid aliases at all (extif-noalias branch)
I will later work on POT_EXTADDR to support more complex/flexible network setups
