### ISSUE TITLE
start-cleanup/stop can interfere with each other

### ISSUE THREAD

**Issue by pizzamig** [pizzamig/pot#152]
**Describe the feature you'd like to have**
pot start contains a cleanup feature, if start fails, but it's also used when a the jail has a blocking start command with non persistent jails.
In this second case, `pot stop` and the start cleanup (who also calls `pot stop`) can mix their effects and some unexpected behavior can happen (i.e. failing to destroy the `epair` twice) 

First, make the execution sequential would help to avoid the code to interfere with each other.
Moreover, it would be useful to relax the assumptions made in the code, make it a bit more robust 

As discussed in #150

**Comment by grembo** [comment]
Serializing is definitely better than having the code execute in parallel.
Ideally, we would ensure that the commands in stop only run once (at least things like post hooks).

How this will play out exactly might also depend on how we change jail start up (e.g., jail start command vs. jexec command).

**Comment by grembo** [comment]
@pizzamig Do you think #155 is sufficient to resolve this?

**Comment by pizzamig** [comment]
Yes, I think is good enough.
I'll close it
