### ISSUE TITLE
Allow flavours to be used without installing them

### ISSUE THREAD

**Issue by davidchisnall** [pizzamig/pot#161]
**Is your feature request related to a problem? Please describe.**

I want to distribute a flavour and a script that runs pot to handle all of the configuration but doing this requires me to install the flavours files.

**Describe the feature you'd like to have**

Either a mechanism for adding extra search directories for flavours or a way of passing the path as part of the -f flag.

**Describe potential alternatives or workaround you've considered (if any)**

Currently, I unconditionally copy files into /usr/local/etc/pot/flavours, which is unsatisfactory.

In the Docker ecosystem, Dockerfiles are the equivalent of flavours.  They can be shipped in the repo along with the thing that is being built and run from there.

**Comment by pizzamig** [comment]
It's a valid point.

I would:
* add the local directory (similar to docker)
* add an option to extend the search patch for flavors

**Comment by grembo** [comment]
> It's a valid point.
> 
> I would:
> 
> * add the local directory (similar to docker)
> * add an option to extend the search patch for flavors
> 
> What would be the most appealing one?

What about (also) adding a parameter to directly specify a flavor (regardless of paths involved? Something like `-F /path/to/flavor’.

**Comment by pizzamig** [comment]
A `-F` option doesn't mix well with `-f`.
You can specify multiple flavor, and they will be applied in order. With `-F` I wouldn't know the order.
But I guess, the usual `-f` can be extended to additionally support pathnames

**Comment by davidchisnall** [comment]
Allowing -f to take a path, possibly with the current working directory included in the search path by default, would be ideal.
