### ISSUE TITLE
Copy out mechanism

### ISSUE THREAD

**Issue by davidchisnall** [pizzamig/pot#162]
**Is your feature request related to a problem? Please describe.**

I want to build a container-like system where some of the container state needs to be initialised from within the container.  Specifically, I am working on some pots for GitHub action runners and want to be able to recreate the pot and reimport the output of the one-time setup that registers the runner.  My desired workflow is:

1. Create a new pot containing the action runner and register it.
2. Discover I want to update the runner or some of the other things in the jail.
3. Recreate the entire thing from a flavour describing the configuration of the pot and import the configuration.

**Describe the feature you'd like to have**

I would like a copy-out analogue of copy-in so that I can copy files out of the jail once the initial setup step has been done and reinject them.  

**Describe potential alternatives or workaround you've considered (if any)**

I considered using mount-in, but I can't use environment variables inside the flavour file and I can't pass explicit arguments to flavours and so I can do this only with a single static location.  I don't know if mount-in is preserved in the final pot either - it is not documented either way and there is no corresponding unmount-in, so I presume it isn't - this is the behaviour that I'd want, mount-in for a single invocation so that the setup script can run the configuration and copy it to the exported folder.

**Comment by bretton** [comment]
I'd like to be able to copy-out generated files for ssh keys, ssl certificates, or even backups. this sounds like a useful feature to have.

**Comment by pizzamig** [comment]
@davidchisnall `mount-in` is a static configuration parameter, the folder/dataset will be always mounted once the `mount-in` command is executed.
I guess you have already checked [here](https://pot.pizzamig.dev/Volumes/) and the explanation wasn't good enough. I'll rework it to make it clearer.
`unmount-in` is a missing feature (currently, I just modify the configuration file, but there is "room for improvements" :sweat_smile:).

In your specific case, the container state needs to be initialised once. While recreating the container, instead of re-initlize it, you want to import the initialized state. Am I correct?

A secure/safe copy-out implementation is complicated, but however possible (probably without globbing, tho)

**Comment by davidchisnall** [comment]
> In your specific case, the container state needs to be initialised once. While recreating the container, instead of re-initlize it, you want to import the initialized state. Am I correct?

Yes, exactly.  The scripts are [here](https://github.com/davidchisnall/act-pot) if you want to look.  The `config.sh` script configures the runner and extracts the config, the `recreate-runner.sh` script regenerates it.  

I am currently just [copying the files out of where `pot` happens to mount the filesystem in my host](https://github.com/davidchisnall/act-pot/blob/56ce156cbd27879d3d16fdff3630c405c40c6970/config.sh#L35) but I'd prefer to have a flavour that's the exact inverse of [the one that imports the config from the host](https://github.com/davidchisnall/act-pot/blob/main/flavours/github-act-import-config).

**Comment by pizzamig** [comment]
I've just wrote an implementation of copy-out.
For obvious reason, the source (inside the pot) needs to be an absolute pathname and it cannot support globbing (pot is a shell script!). You can copy out a single file or a directory.
I will run some further tests, but it seems working...

**Comment by davidchisnall** [comment]
That sounds great.  Once that's in the version in packages, I can start using it in our CI system.
