### ISSUE TITLE
Please enable /dev/tty for jail to jail ssh without host verification error

### ISSUE THREAD

**Issue by bretton** [pizzamig/pot#164]
**Is your feature request related to a problem? Please describe.**
I am unable to ssh from one jail to another jail on same host, or between hosts. 
I am unable to ssh to self within a jail. 
However I can ssh to the jail from parent host or an external host.

Problem with ssh-to-self or jail-to-jail is:
```
debug1: read_passphrase: can't open /dev/tty: No such file or directory
Host key verification failed.
```

**Describe the feature you'd like to have**
I would like to be able to ssh from one jail to another, or sftp, without getting the error `Host key verification failed.`

**Describe potential alternatives or workaround you've considered (if any)**
I've tried with ssh keys for access, but it doesn't help, still a /dev/tty error.
I've explicitly set ignoring host verification, but this doesn't address the problem of no /dev/tty on the jail.

**Comment by grembo** [comment]
@bretton I don't see this issue here, maybe that's specific to your setup?

Does your jail/pot have devfs mounted? Which FreeBSD version and which version of pot?

**Comment by bretton** [comment]
> Does your jail/pot have devfs mounted? Which FreeBSD version and which version of pot?

pot version: 0.11.6
FreeBSD 13.0-RELEASE

from parent OS (bhyve vm running FreeBSD 13.0-RELEASE)
```
# mount -t devfs
devfs on /dev (devfs)
devfs on /opt/pot/jails/flavour-clone/m/dev (devfs)
```

from within pot jail "flavour-clone"
```
root@flavour-clone:~ # mount -t devfs
root@flavour-clone:~ # ls /dev
crypto  fd      null    random  stderr  stdin   stdout  urandom zero    zfs
```

the pot-generated jail.conf has the following (split multi line for readability):
```
jid=2
allow.set_hostname=false
allow.raw_sockets
allow.socket_af
allow.sysvipc
allow.chflags
exec.clean
mount.devfs
sysvmsg=new
sysvsem=new
sysvshm=new
enforce_statfs=2
children.max=0
name=flavour-clone
host.hostname=flavour-clone.hostname
osrelease=13.0-RELEASE-p3
path=/opt/pot/jails/flavour-clone/m
persist ip4.addr=10.0.0.1
exec.start="sh /etc/rc"
ip4.addr=vtnet0|10.0.0.1
```

How do I get/set a pot jail to see all of devfs?

Will update to latest version pot :)

**Comment by grembo** [comment]
Well, you don't really want to see all of devfs (e.g., no raw disk devices). Really depends on the jails devs_rules configuration.

In the environment I tested on (using the pot pkg), "ls /dev" doesn't show /dev/tty, but "ls /dev/tty" does :/

**Comment by bretton** [comment]
No luck with newer version pot, same issue with /dev/tty

from within a pot jail
```
# ls /dev/tty
ls: /dev/tty: No such file or directory
```

I'm not seeing an easy way to set the pot jail's devfs_rules?

**Comment by grembo** [comment]
devfs_rulesets are a bit weird - if none is specified when creating a jail, ruleset 4 is assigned.

See this code snippet from https://cgit.freebsd.org/src/tree/usr.sbin/jail/command.c?h=releng/13.0#n533 :

```c
	ruleset = string_param(j->intparams[KP_DEVFS_RULESET]);
	if (!ruleset)
	    ruleset = "4";	/* devfsrules_jail */
```

Unfortunately the [man page](https://www.freebsd.org/cgi/man.cgi?query=jail&apropos=0&sektion=0&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html) section on `devfs_ruleset` is a bit confusing on this, but the part on `mount.devfs` is clear about it:

```
mount.devfs
	     Mount a devfs(5) filesystem on the	chrooted /dev directory, and
	     apply the ruleset in the devfs_ruleset parameter (or a default of
	     ruleset 4:	devfsrules_jail) to restrict the devices visible in-
	     side the jail.
```

AFAIK pot doesn't mess with devfs rulesets at all, so all pots should have devfs ruleset 4 by default.

This means, as long as there is no explicit devfs_ruleset set on your jail (and in the output of "jls -nj flavour-clone"), you can assume that ruleset 4 is used.

You can check what's in ruleset 4 on your host using `devfs rule -s <setnum> show`, e.g.,

    # devfs rule -s 4 show
    100 include 1
    200 include 2
    300 include 3
    400 path fuse unhide
    500 path zfs unhide

You can see the active rules on a mounted devfs filesystem using the devfs command, with the -m parameter, e.g.:

    # devfs -m /opt/pot/jails/flavour-clone/m/dev rule show
    100 include 1
    200 include 2
    300 include 3
    400 path fuse unhide
    500 path zfs unhide

(so in this case, the rules in ruleset 4 and on the mountpoint are identical in content).

Looking at the included rulesets, you see that there should be a lot of things that are visible within your jail. Note that includes aren't recursive (so you can only include one level in these rulesets).

I'm not aware how to check which ruleset is set on a jail (only indirectly by inspecting rules or if a different one was set by specifying a parameter on the jail command, which might make sense for pot anyway). Maybe pot should explicitly specify 4, just so it's in the jail parameters.

Now, if checking all those things on your machine (especially rulesets 1, 2, 3) won't help, you could simply try to run `service devfs restart` and see if this fixes things for you.

**Comment by bretton** [comment]
@grembo thanks for the feedback, will go through everything and test in environment with the issue.

for completeness I setup another environment with a sample pot image which can run ssh server or act as client.

I've had no problems with ssh connections from jail to jail, on a KVM virtual machine running Freebsd 13 with latest pot. 

This confirms the issue is with bhyve virtual machines, running pot jails. Only external access allowed. Can't ssh to self within a jail, can't ssh between jails, due to the /dev/tty issue.

**Comment by bretton** [comment]
for vm-bhyve virtual machines, the solution to expose /dev/tty in a jail is to run the following **once the pot jail has started** from the parent OS:
```
devfs -m /opt/pot/jails/<pot name>/m/dev/ rule apply type tty unhide
```

**Comment by grembo** [comment]
@bretton Did you double check your vms devs rules setup though (like described above)? This really shouldn’t be necessary (and if it is, there is probably an underlying issue that needs to be fixed).

**Comment by bretton** [comment]
> Did you double check your vms devs rules setup though (like described above)? 

@grembo 
```jls``` out says `devfs_ruleset=0` and I don't know how to specify the correct ruleset

output
```
devfs -m /opt/pot/jails/sample-server/m/dev rule show

100 include 1
200 include 2
300 include 3
400 path fuse unhide
500 path zfs unhide
```

output
```
root@bhyve:~ # jls -nj sample-server
devfs_ruleset=0 nodying enforce_statfs=2 host=new ip4=disable ip6=disable jid=53 name=sample-server osreldate=1300139 osrelease=13.0-RELEASE-p3 parent=0 path=/opt/pot/jails/sample-server/m persist securelevel=-1 sysvmsg=new sysvsem=new sysvshm=new vnet=inherit allow.chflags allow.nomlock allow.nomount allow.mount.nodevfs allow.mount.nonullfs allow.mount.noprocfs allow.mount.notmpfs allow.mount.nozfs allow.noquotas allow.raw_sockets allow.noread_msgbuf allow.reserved_ports allow.noset_hostname allow.socket_af allow.suser allow.sysvipc allow.unprivileged_proc_debug children.cur=0 children.max=0 cpuset.id=3 host.domainname="" host.hostid=0 host.hostname=sample-server.bhyve host.hostuuid=00000000-0000-0000-0000-000000000000 ip4.addr=10.0.0.2 ip4.saddrsel ip6.addr= ip6.saddrsel
```

output
```
root@bhyve:~ # cat /tmp/sample-server.jail.conf 
jid=53  allow.set_hostname=false        allow.raw_sockets       allow.socket_af allow.sysvipc   allow.chflags   exec.clean      mount.devfs     sysvmsg=new     sysvsem=new     sysvshm=new     enforce_statfs=2        children.max=0  name=sample-server      host.hostname=sample-server.bhyve        osrelease=13.0-RELEASE-p3       path=/opt/pot/jails/sample-server/m     persist ip4.addr=10.0.0.2     exec.start="sh /etc/rc" ip4.addr=vtnet0|10.0.0.2
```

the command I gave solves my immediate issue so I can continue with what's been delayed. Not sure where else to look to make it work normally?

**Comment by grembo** [comment]
> `jls` out says `devfs_ruleset=0` and I don't know how to specify the correct ruleset

Yeah, that's a bit unfortunate/suboptial, as this is the configured one, not the one that is applied (as devfs_ruleset = 0 makes jail apply devfs_ruleset 4), which is something`devfs -m /opt/pot/jails/sample-server/m/dev rule show` also confirms - you are using ruleset 4.

Setting it to 4 explicitly on pot start would be a good thing to make things more obvious, I'll look into that. Changing FreeBSD in that respect would be useful too, but probably a lot more work.

That said, can you confirm these results within your bhyve vm?

```
# devfs rule -s 1 show | md5
9e19f438fb140bb674f2cad521114fdc
# devfs rule -s 2 show | md5
05e218d78d4951d64b2373cbfb15fd2a
# devfs rule -s 3 show | md5
e5a0d8b52d0ab4e7904c4a7907d592d7
# devfs rule -s 4 show | md5
9208b8738eb6abb2b3423d535c07e38c
```

This definitely isn't pot specific and it your conclusion that this might be due to bhyve sounds plausible.

I'll try to reproduce it locally and see if I can make sense of it (maybe it's related to vm-bhyve and the way the getty/serial console is used?).

**Comment by bretton** [comment]
> That said, can you confirm these results within your bhyve vm?

I get the same results
```
# devfs rule -s 1 show | md5
9e19f438fb140bb674f2cad521114fdc
# devfs rule -s 2 show | md5
05e218d78d4951d64b2373cbfb15fd2a
# devfs rule -s 3 show | md5
e5a0d8b52d0ab4e7904c4a7907d592d7
# devfs rule -s 4 show | md5
9208b8738eb6abb2b3423d535c07e38c
```

**Comment by grembo** [comment]
@bretton I can reproduce the issue here too (FreeBSD13 + vm-bhyve + pot + ssh).

**Comment by bretton** [comment]
awesome, will re-open and leave open so long

**Comment by grembo** [comment]
@bretton The problem only exists when connecting to the bhyve vm using `vm console`. When using `ssh` to get into the VM it works just fine. The main difference is the tty device used in both cases.

Here you can see two simultaneous connections, one where things work okay and one where they don't (non-ssh vs ssh):

```
 4:03PM  up  3:02, 2 users, load averages: 0.27, 0.21, 0.28
USER       TTY      FROM       LOGIN@  IDLE WHAT
root       u0       -          4:00PM     - w -n
user       pts/0    10.1.1.1   4:02PM     - -su (csh)
```

As you can see, in one case the device is pts/0 (which works), while device u0 won't.

This is due to rules in ruleset 2, which is included by ruleset 4:

```
[root@bretton ~]# devfs rule -s 4  show
100 include 1
200 include 2
300 include 3
400 path fuse unhide
500 path zfs unhide
[root@bretton ~]# devfs rule -s 3  show
100 path ptyp* unhide
200 path ptyq* unhide
300 path ptyr* unhide
400 path ptys* unhide
500 path ptyP* unhide
600 path ptyQ* unhide
700 path ptyR* unhide
800 path ptyS* unhide
900 path ptyl* unhide
1000 path ptym* unhide
1100 path ptyn* unhide
1200 path ptyo* unhide
1300 path ptyL* unhide
1400 path ptyM* unhide
1500 path ptyN* unhide
1600 path ptyO* unhide
1700 path ttyp* unhide
1800 path ttyq* unhide
1900 path ttyr* unhide
2000 path ttys* unhide
2100 path ttyP* unhide
2200 path ttyQ* unhide
2300 path ttyR* unhide
2400 path ttyS* unhide
2500 path ttyl* unhide
2600 path ttym* unhide
2700 path ttyn* unhide
2800 path ttyo* unhide
2900 path ttyL* unhide
3000 path ttyM* unhide
3100 path ttyN* unhide
3200 path ttyO* unhide
3300 path ptmx unhide
3400 path pts unhide
3500 path pts/* unhide
3600 path fd unhide
3700 path fd/* unhide
3800 path stdin unhide
3900 path stdout unhide
4000 path stderr unhide
```

As you can see, pts/* is included, that's why it works when sshing into the VM

```
3500 path pts/* unhide
```

while ttyu* is not.

An easy way to correct this is to add ttyu* to ruleset 3 and restart the pot.

```
devfs rule -s 3 add 4100 path "ttyu*" unhide
pot stop mypot
pot start mypot
```

Now things work as expected.

Which leads to two ways to resolve the issue:
1. Just ssh into VMs instead of using the serial console
2. Change ruleset 3 permanently on disk

I assume that as this only happens when connecting over serial console, nobody really noticed it so far.

I'll check on the mailing list if it would make sense to modify the ruleset permanently to include ttyu*.

**Comment by bretton** [comment]
@grembo that's great, thanks a lot!

**Comment by bretton** [comment]
> Which leads to two ways to resolve the issue:
>     1. Just ssh into VMs instead of using the serial console
>     2. Change ruleset 3 permanently on disk

ssh in only partially addresses the issue, as ssh/sftp connections in the pot image boot process will fail with host key error if /dev/tty not enabled.

**Comment by grembo** [comment]
> > Which leads to two ways to resolve the issue:
> > 1. Just ssh into VMs instead of using the serial console
> > 2. Change ruleset 3 permanently on disk
> 
> ssh in only partially addresses the issue, as ssh/sftp connections in the pot image boot process will fail with host key error if /dev/tty not enabled.

I think it should be fine as long as pot is started within the ssh session or from boot (which also should have a valid tty).

**Comment by grembo** [comment]
@bretton We dived a bit deeper into this issue in a different context: https://lists.freebsd.org/archives/freebsd-hackers/2022-February/000838.html

So, besides the ways to work around described above, there's also the option to run commands through something that creates a new pty like `script /dev/null <command>`.
