### ISSUE TITLE
Can I unmount a zfs dataset from a pot?

### ISSUE THREAD

**Issue by f8122dac91** [pizzamig/pot#170]
**Is your feature request related to a problem? Please describe.**
I have a running pot with a zfs dataset mounted somewhere on its rootfs, which was mounted with `mount-in` command. Now, I need to move the mountpoint to another path but I'm failing to find any info on how to unmount a zfs dataset from a pot.

**Describe the feature you'd like to have**
`mount-out` or `unmount` command for unmounting a dataset/fscomp/directory would be great. Or a documentation entry that explains how to remove a dataset from a pot would work too.

**Describe potential alternatives or workaround you've considered (if any)**
None I can think of.

**Comment by pizzamig** [comment]
Hi.
Unmount (or mount-out) is a missing feature. I recently implemented copy-out, but I guess it's time to implement mount-out as well.

Did you use `mount-in` with the `-w` option (re-mount)?
Do you need to `umount` it while `pot` is still running?

The -w option will change the mountpoint of the dataset. Without it, it will use `nullfs`
