### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by pizzamig** [pizzamig/pot#34]
Support IPv6 networks

**Comment by pizzamig** [comment]
Currently, `-i inherit` has support of ipv6
Soon static IP (`-s`) will receive ipv6 support.
IPv6 on in internal virtual network will require a lot of work

**Comment by Crest** [comment]
How much work would be required to support dual stack with the alias network type? From a first look at the code just supporting multiple addresses should be enough.

**Comment by pizzamig** [comment]
yes, that is what is missing.
Currently IPv4 or IPv6 are mutually excluded for alias network type.
dual stack is a thing I'm working on for the next release.
Unfortunately it's quite time-consuming, because I have to touch more or less everything, the initial assumption is to have 1 IP only... However `jail(8)` already support dual stack, so I think it's just matter of time

**Comment by mathiasp** [comment]
Any chance for alias with configurable network device? Background: my new setups will start to handle v4 as strictly legacy: it's only active at the edges, for legacy clients which still do not have v6. Internally, everything will be v6. I would still like to put the jails on a bridge, as a first shot I thought with an alias-type and a manually configured bridge with public v6 addresses, which I could use with alias *iff* I could define the bridge as target. 

I also think using v6 in the documentation examples might be useful to switch one's thinking about v4/v6.

**Comment by pizzamig** [comment]
Hi.
Recently I had a chat with people with far more experience than me.
Now I've a clear idea about how to add dual stack support and better IPv6 support in general.
I will work on this soon.
I can also work on add a way to select a network interface different than the default one.

**Comment by pizzamig** [comment]
@mathiasp Alias with configurable network device is done and released in version 0.10.4
The create command has now an option `-I netif` to specify a different network interface. The option is valid only for alias.
For instance:
```
pot create -p test -b 12.1 -N alias -i 2a00::1 -I em1
```
will create a pot that will use `em1` as network interface with IPv6 address `2a00::1`

**Comment by pizzamig** [comment]
The feature requested in this issue has been release in version `0.11.0`
Documentation about flexible alias configuration and network stack support is available [here](https://pot.pizzamig.dev/Network)

While here, I close the ticket
