### ISSUE TITLE
###>  no snapshot found for zroot/pot/jails/salt-base/custom

### ISSUE THREAD

**Issue by OleM2k** [pizzamig/pot#38]
I was playing on the pot_slides.pdf file on page 15:
```sh
pot init
pot create-base -r 11.1
pot create-fscomp -f repository
pot create -p saltmaster -b 11.1
pot add-fscomp -p saltmaster -f repository -m /mnt
pot create-fscomp -f repo-work
pot create-fscomp -f repo-home
pot create -p salt-base -b 11.1
pot create -p salt-work -P salt-base -l 2
###>  no snapshot found for zroot/pot/jails/salt-base/custom
```
VBox FreeBSD both 11.1 and 12

 :confused:

**Comment by pizzamig** [comment]
ups... The slides are missing a step and this error message is not really helpful. Thanks for reporting
After the creation of salt-base, a snapshot is needed to be used as reference for other pots.
To create a snapshot, you can use the command:

```
pot snapshot -p salt-base
```

**Comment by OleM2k** [comment]
If nature were not mistaken, humanity would not appear!
So the mistakes are very natural!
Thank you for the pots.
I want to make pots with Apache, Nginx, PHP, databases, CMS-s...
And try to combine it all.
Like in Docker.
So I'll have a lot of mistakes and I'll write a lot.

Bye!

**Comment by pizzamig** [comment]
please, do it!
That is a use case I've thought, but not tested yet.
Go go go!
