### ISSUE TITLE
pot ls doesn't list the pot if there is only one pot

### ISSUE THREAD

**Issue by nkfilis** [pizzamig/pot#52]
after `pot create-base -r 11.2` and `pot create -p foo1 -b 11.2` I ran `pot ls` and it shows only `base-11_2`, after running `pot create -p foo2 -b 11.2` it shows `base-11_2` and both pots foo1 and foo2.

**Comment by nkfilis** [comment]
after `pot create-base -r 11.2` and `pot create -p foo1 -b 11.2` I ran `pot ls` and it shows only `base-11_2`, after running `pot create -p foo2 -b 11.2` it shows `base-11_2` and both pots foo1 and foo2.

**Comment by pizzamig** [comment]
nice catch!
