### ISSUE TITLE
on boot start flag for pot

### ISSUE THREAD

**Issue by Johanhen** [pizzamig/pot#54]
Would it be possible to set a flag on a pot so that it will start at boot time.
If one has many pots, a line in /etc/rc.conf with pot_list=" " would become a little messy.
A on boot flag on a pot is a nicer option in my opinion.

Thanks for all your work on pot.

**Comment by pizzamig** [comment]
This feature is completed, however I'm not 100% satisfied.
I've implemented 2 commands (set-attribute and get-attribute)
The attribute "start-at-boot" will start the pot automatically via rc script (not just at boot, but using `service pot start`). Probably it's better to use a different name (auto-start? start-with-rc? rc-enabled?)
What do you think?

**Comment by pizzamig** [comment]
implemented with the attribute `start-at-boot`.
Even if not a perfect name, it's somehow done

**Comment by Johanhen** [comment]
Thanks, i will try it out when i get back from vacation.

Op di 30 jul. 2019 om 11:57 schreef Luca Pizzamiglio <
notifications@github.com>
