### ISSUE TITLE
Support for pre/post start and stop

### ISSUE THREAD

**Issue by urosgruber** [pizzamig/pot#61]
I'm new here and didn't have time to review the code but is there any support to attach sort of a pre, post hooks during start and stop commands? If so how can this be done.

And second question how can I pass a list of env variables to the script as well as inside pot container?

**Comment by urosgruber** [comment]
So for the hooks. I think jail already have `exec.prestart`, `exec.poststart`and `exec.prestop`, `exec.poststop`. I'm using this functionality to deal with different kind of things. For example some `pfctl` custom stuff, service registration, cleanup, notification for other services etc. I'm not sure if supportfor the folder of scripts is actually possible out of the box, but would be something that could be userful.

Regarding env variables it would be nice to expose variables like, pot name, ip, jid etc. as a ENV variable to be used inside hooks. In addition heaving a list of env variables specified to be used  inside jail. I think the two need to be separated as we don't want to expose this.

**Comment by pizzamig** [comment]
yes, jails already have their exec to be executed in the host system.
However, I'm supporting:
* non-persistent jails (`stop` hooks won't be executed, if jails disappear when there no processes left)
* `exec.start` that won't fork in background (`poststart` won't be executed)
Those 2 features (a big difference between a typical jail use case and a modern container use case) make the hooks quite counter-intuitive.
About service registration (that can be executed inside the jail), we are working on `nomad` integration (https://github.com/trivago/nomad-pot-driver) to have many features available for free (automatic `consul` integration for service registration and discovery, for instance)
I tend to avoid hooks, but to provide the needed features instead out-of-the-box. It's a trade-off between usability (less detail to care) and customization (less ability to customize), but I see your point. Theoretically, hooks shouldn't be so hard to implement and I could even develop many new features as hooks, simplifying the internal structure. However, especially the `stop` hooks are really misleading for people not used to work with jails.

about environment variables, I agree, those are two distinct features:
* a set of variables, with fixed names, that describes the container
* a feature to pass environment variables from the host to the container

I'll see what I can do...

**Comment by urosgruber** [comment]
Never thought about the non-persistnat jails. And I didn't know stop/prestop is not executed. Right now the only thing I use this stop is to remove some stuff from PF anchors and tables. Because all the traffic is blocked between jails unless specified as a dependency jail. 

I'm still playing with pot to see if it's usable in my use case without big refactoring because of a different concept.

**Comment by pizzamig** [comment]
pre/post stop are executed if you use `jail stop`, because they are executed by the jail command itself. There is no "daemon" that executed callbacks/hooks.
Currently we are using non-persistent jails with `nomad` and the nomad-pot-driver is invoking `pot stop` if the jail disappear, so we can clean up, but it's not a general solution.

**Comment by pizzamig** [comment]
I've just committed an easy implementation to set pre/post start/stop hooks.
It's only available in master, I'll release once I have add proper documentation.
For now, the scripts have environment variables set as:
_POT_NAME
_POT_IP (if applicable)
_POT_BRIDGE (bridge name for private-bridge, but I'd like to add the bridge interface, if used)
_POT_JID (if applicable)

Is there some other information do you like to have included?

**Comment by urosgruber** [comment]
@pizzamig that is awesome. Let me have a look at what variables I currently use and I'll add a comment in a day or two.

**Comment by pizzamig** [comment]
I'm gonna closing this, the feature has been implemented and, if anything is missing, a new issue can be opened
