### ISSUE TITLE
pot stop prints "pfctl: /dev/pf: No such file or directory"

### ISSUE THREAD

**Issue by 0mp** [pizzamig/pot#65]
I get:

> pfctl: /dev/pf: No such file or directory

as an output of `pot stop mypot`.

I didn't configure anything in particular, just pot init and pot create.

Also, the pf kernel module is not loaded (which is most likely the reason for this warning to be printed).

**Comment by pizzamig** [comment]
Thanks for reporting. It's kind of a false positive message, but `pfctl` should be invoked only if `pf` is up and running.
This patch should solve it:
```
diff --git a/share/pot/stop.sh b/share/pot/stop.sh
index 19c3aab..210967c 100644
--- a/share/pot/stop.sh
+++ b/share/pot/stop.sh
@@ -51,7 +51,9 @@ _js_stop()
                        fi
                fi
        fi
-       pfctl -a "pot-rdr/$_pname" -F nat -q
+       if [ -c "/dev/pf" ]; then
+               pfctl -a "pot-rdr/$_pname" -F nat -q
+       fi
 
        if [ -r "$_jdir/ncat.pid" ]; then
                pkill -F "$_jdir/ncat.pid" "ncat-$_pname"
```
can you please try the patch?

**Comment by 0mp** [comment]
Patch works. Thanks!
