### ISSUE TITLE
pot jails of type 'single' have wrong permissions on /tmp

### ISSUE THREAD

**Issue by grembo** [pizzamig/pot#72]
This only affects jails of type 'single' and breaks anything not running as root and expecting to be able to write to /tmp.

```
root@jailhost:~ # pot create -b 12.0 -t single -p tmptest
root@jailhost:~ # pot run tmptest
root@jailhost:~ # su -m nobody -c "touch /tmp/somefile"
touch: /tmp/somefile: Permission denied
root@tmptest:~ # ls -ald /tmp
drwxr-xr-x /tmp
```

This can be fixed by running chmod:

```
root@tmptest:~ # chmod 1777 /tmp
root@tmptest:~ # ls -ald /tmp
drwxrwxrwt /tmp

```

**Comment by pizzamig** [comment]
Thanks for reporting! The suggested fix has been committed.
I have to admit that I'm not yet focused on non-root use cases, then more small issues can be found
