### ISSUE TITLE
sysutils/pot: Install documentation by default

### ISSUE THREAD

**Issue by 0mp** [pizzamig/pot#74]
It would be cool if the existing documentation was installed by default with the pot package.

**Comment by grembo** [comment]
A man page (even if it's basic) would be really nice.

**Comment by pizzamig** [comment]
yeah, I forgot to add the existing documentation in the port. I'll do in the next release.
About the man page, yes, it would be really nice.
However, writing and maintaining a man page it's quite time consuming.
Do you know, if there is a way to convert markdown to mandoc? Or from other sources?

I'd like to have an approach similar to doxygen, where I put the man page inside the code, but I'm not aware if it's doable. IIRC Doxygen support for man pages is API oriented (section 3)

**Comment by grembo** [comment]
I'm not aware of a good in-code tool, especially from a shell script. I'm not a fan of doxygen anymore though. pandoc is a fantastic tool, unfortunately it's a **huge** dependency, so I would recommend against solutions that make use of it.

I used sphinx-doc to create man pages in the past, you can see an example of how to write man pages with it here: http://www.sphinx-doc.org/en/1.8/_sources/man/sphinx-build.txt

A more complex example of the same page can be found here:
https://www.sphinx-doc.org/en/master/_sources/man/sphinx-build.rst.txt

Sphinx-doc uses reStructured text by default.  It also supports markdown, but rst is a lot more expressive and probably a better solution. Sphinx-doc is used by many projects, so it's installed on most FreeBSD boxes anyway. As a plus, github can render it , as you can see here https://github.com/sphinx-doc/sphinx/blob/master/doc/man/sphinx-build.rst

Simple idea to maintain the man page in code: Implement something like  "pot doc" that outputs rst from within the script (and maybe also the includes) and is fed into sphinx-doc during the build process.

I could do a simple example implementation of that for you (sphinx-doc config, port skeleton, pot doc target...) to show how that would work in practice.

**Comment by pizzamig** [comment]
I've released 0.10.1 with some fixes, but I didn't have time yet to improve the man page, so I left it out for now.
In the port I added the md documents, as documentation.
I should have some time to work on man pages soon

**Comment by pizzamig** [comment]
Documentation (md files) is currently installed and part of the package.
I'll close this issue, a specific one related to man pages already exists
