### ISSUE TITLE
[BUG] Pot create ignores the exit status from flavour scripts

### ISSUE THREAD

**Issue by Crest** [pizzamig/pot#84]
**Describe the bug**
The `pot create -f $flv` command executes a the `${_flv}.sh` script in `/usr/local/etc/pot/flavours/` to customize the jail. These scripts can fail (e.g. a package fails to install). Pot ignores the exit status from the flavour creation script resulting in a partially configured jail.

**To Reproduce**
1. Define a flavour with a helper shell script.
2. Cause the shell script to fail e.g. remove a package the script attempts to install from the package repo.
3. Create a pot using said favour.
4. The execution reaches the `_cj_flv` function of `create.sh`.
5. The function detects the existence of an executable named `${_flv}.sh` in the flavours directory, copies it into the jail's `/tmp` and runs it with `jexec ${_pname} ...`
6. The exit status of jexec gets ignored.

**Expected behavior**
I expect `pot create -f` to check the script exit status and treat every status except 0 as a fatal error. I would prefer pot to rollback the partial jail creation by default, but offer an option to keep the jail in its failed state for debugging purposes.

**Comment by pizzamig** [comment]
Thanks for reporting
While here, I've implemented a generic cleanup function if create fails also in other places or if you interrupt it  with a CTRL+c.
To keep the partial/broken pot, a `-k` has been added to the create command.
If it's OK, we can close this issue

**Comment by Crest** [comment]
Thanks for fixing this.
