### ISSUE TITLE
[BUG] The fbsd-update flavour included in pot only works from a tty

### ISSUE THREAD

**Issue by Crest** [pizzamig/pot#86]
**Describe the bug**
By default the freebsd-update fetch command refuses to run without a controlling tty. It does this to protect the FreeBSD project infrastructure from DoS attacks by stupid cron jobs running `freebsd-update fetch` with insufficient jitter to spread the load.

This is a problem for pot because the fbsd-update flavour does something that looks the same to freebsd-update unless the pot starts with a controlling tty. Ansible's command module runs commands without a controlling tty causing `pot create -f fbsd-update …` to fail.

**To Reproduce**
1. Attempt to create a `pot` with this command: 'pot create -f fbsd-update …' without a controlling tty.
2. The flavour fails as `freebsd-update fetch` refuses to fetch updates causing `freebsd-update install` to fail because nothing has been fetched.

**Expected behavior**
I expect the flavour to work without a tty. This can be achieved by passing `--not-running-from-cron` to `freebsd-update`. The fetch and update commands could also be combined and prefixed with `exec`. This would simplify the flavour to `exec env PAGER=cat freebsd-update --not-running-from-cron fetch install`.

**Comment by pizzamig** [comment]
Thanks for the report! Fix already committed
