### ISSUE TITLE
[BUG] Pot prepare is broken in pot 0.11

### ISSUE THREAD

**Issue by Crest** [pizzamig/pot#88]
**Describe the bug**
Pot 0.11 introduced the new 'pot.stack' parameter to jail configurations. Pot prepare creates a jail 'pot.conf' with two 'pot.stack=ipv4' lines breaking `pot start $jail`. It doesn't create the epair interface required to attach the jail to the public bridge.

**To Reproduce**
1. Create a pot with network type inherit.
2. Export the pot as image.
3. Prepare a jail from the image.
4. Start the jail.
5. The enter the jail and run `ifconfig -l`.
6. Run `ifconfig -l` on the host.
7. There neither contain either end of an epair interface for the jail.
8. Run `fgrep pot.stack $jail_pot_conf | wc -l` on the jail pot.conf. It returns two instead of the expected single line.
9. Manually removing one of the offending 'pot.stack=ipv4' lines allows the jail to start as expected.

**Expected behavior**
Pot prepare should continue to work like it did in pot 0.10. It should create a epair, add one end to the bridge and pass the other end to the jail's network stack. Extending the new support for IPv6 and IPv6+IPv4 to prepared jails would be nice to have.

**Comment by pizzamig** [comment]
Thanks for reporting. `prepare` is not yet part of the CI and I didn't detected this regression.
It's a bug in `clone`, a fix is on the way

While here, I'm going to add the -S option for the network stack to `prepare` as well

**Comment by pizzamig** [comment]
Tests are successful, I'm preparing a fix release.

**Comment by Crest** [comment]
The bugfix added a new bug. A pipe at the end of the line is missing causing two grep calls to be combined into one grep call with the arguments of both.
