### ISSUE TITLE
[BUG] Pot temporary files in the host /tmp are world readable.

### ISSUE THREAD

**Issue by Crest** [pizzamig/pot#89]
**Describe the bug**
Pot creates a world readable temporary file named '/tmp/pot_environment_${name}.sh' containing the jail environment variables. This leaks data to all users on the host system with read access to '/tmp'.

**To Reproduce**
1. Create the `pot` with this command: `pot create -v -p test -N alias -S ipv6 -t single -b 12.1 -f fbsd-update -i 'em0|2001:db8::2'`
2. Start the pot.
3. Read the file as nobody with: `sudo -u nobody cat /tmp/pot_environment_test.sh`

**Expected behavior**
I expect one root and wheel to have access to the file.

**Additional context**
I looks like pot just overwrites those files and doesn't delete them after they have been used to start jails. This means that the leak persists until '/tmp' is cleared.

**Comment by grembo** [comment]
@pizzamig I couldn't see anything about this in the commit: Did this also fix file permissions? (the world readable temporary file could still be read the moment the pot starts)

**Comment by pizzamig** [comment]
In the start command, after I copied the file inside the jail, I just delete it (`rm $_shfile`)

**Comment by Crest** [comment]
It still leaves the files world readable for a few seconds. Is there any reason not to limit access to "root:wheel"?

**Comment by grembo** [comment]
@Crest @pizzamig I opened #91 to address this.

Note that you could also use `mktemp -t` to make use of $TMPDIR (right now this doesn't seem to be a pattern you're following).

Leaking information isn't good, even if it's just for a few seconds. The file name was predictable, so having a trigger to extract information from it was quite trivial.

The reason why having predictable file names for temporary files isn't that great is described well on the [mktemp man page](https://www.freebsd.org/cgi/man.cgi?query=mktemp&sektion=1).

> The mktemp utility is provided to allow shell scripts to safely use 
> temporary files.  Traditionally, many shell scripts take the name of the
> program with the pid as a suffix and use that as a temporary file name. 
> **This kind of naming scheme is predictable and the race condition it creates
> is easy for an attacker to win.**  A safer, though still inferior, approach is
> to make a temporary directory using the same naming scheme.  While this does
> allow one to guarantee that a temporary file will not be subverted, it still
> allows a simple denial of service attack.  For these reasons it is suggested
> that mktemp be used instead.

**Comment by pizzamig** [comment]
Background:
* I admit that I didn't put security at the first place
* I needed predictable names for unit test purposes, so I could analyze the output

With that said:
* mktemp is the way to go
* using restricted mod is also a good valid point

**Comment by grembo** [comment]
> Background:
> 
> * I admit that I didn't put security at the first place
> * I needed predictable names for unit test purposes, so I could analyze the output
> 

I have an idea about that, I’ll update my pull request based on that (it’s trivial).


> With that said:
> 
> * mktemp is the way to go
> * using restricted mod is also a good valid point
