### ISSUE TITLE
[BUG] Pot mount-in doesn't work on stopped jails

### ISSUE THREAD

**Issue by Crest** [pizzamig/pot#93]
**Describe the bug**
The pot mount-in -f $fscomp -p $pot -m command

**To Reproduce**
1. Create a pot with: `pot create -v -p test -f fbsd-update -t single -N alias -S ipv6 -i 'em0|2001:db8::2'`
2. Create a filesystem component with: `pot create-fscomp -v -f comp`
3. Make sure the pot is stopped: `pot stop test`
4. Combine the jail and fscomp: `pot mount-in -v -p test -f comp -m /mnt`
5. Enjoy the chaos.

This is the output of `mount | grep /comp`:
```
zroot/pot/fscomp/comp on /pot/fscomp/comp (zfs, local, noatime, nfsv4acls)
/pot/fscomp/comp on /pot/jails/test/m/=====> (nullfs, local)
```
and the fscomp.conf is badly mangled:
```
zroot/pot/fscomp/comp /pot/jails/test/m/=====>  mount /pot/jails/test/m/tmp
=====>  unmount /pot/jails/test/m/tmp
=====>  /pot/jails/test/m/dev is already unmounted
/mnt
```
**Expected behavior**
I expect the fscomp to be added to the jail's fscomp.conf and either mounted immediately or as part of the jail start. It does work as long as the jail is running.

**Comment by pizzamig** [comment]
I found the error.
As workaround, if you avoid the flag `-v` in `mount-in` it will work.

I'm working on a more robust fix for this
