### ISSUE TITLE
[BUG] Pot clone doesn't preserve hooks.

### ISSUE THREAD

**Issue by Crest** [pizzamig/pot#94]
**Describe the bug**
Pot clone doesn't preserve hooks.

**To Reproduce**
1. Create a pot with: `pot create -v -p original -t single -b 12.1 -f fbsd-update`
2. Set a hook on the pot with:
```
cat >prestart.sh <<'EOF'
#!/bin/sh
echo "I'm a prestart hook."
EOF
chmod +x prestart.sh
pot set-hook -v -p original -s prestart.sh
```
3. Check that the prestart hook got installed into `/pot/jails/original/conf/prestart.sh`.
4. Clone the orignal pot (taking a snapshot on the fly): pot clone -v -p clone -P original -F
5. There are no hooks in `/pot/jails/clone/conf`.

**Expected behavior**
I expected pot clone to preserve hooks. I encountered this when I created pot images with hooks and created instances of the images with `pot prepare`. The imported images contained the hooks, but the clones created by prepare lost the hooks. I want to use the hooks to add/remove pots to/from PF tables and automatically create filesystem components for shared state between all instances of an image on the same jail host.

From a look into `zpool history` and quick glance into `clone.sh` it looks like `pot clone` only clones the `m` dataset. To preserve hooks it would have to copy them from the original `conf/` directory to the clone `conf/` directory.

**Comment by pizzamig** [comment]
Thanks for reporting. I've found the bug.
`clone` is cloning the filesystem, but the configuration files are copied and modified on the fly.
Hooks have been forgotten.
A fix is on the way
